//if API Call fails then we can use reserve keywords
//fallback time:- Tessaract.js will be used
//if api fails then also tessaract will be used.

module.exports = {
  ROLES: {
    ADMIN: 'admin',
    MANAGER: 'manager',
    EMPLOYEE: 'employee'
  },
  STATUS: {
    PENDING: 'pending',
    APPROVED: 'approved',
    REJECTED: 'rejected'
  },
  RULE_TYPES: {
    SEQUENTIAL: 'sequential',
    PERCENTAGE: 'percentage',
    SPECIFIC: 'specific',
    HYBRID: 'hybrid'
  },

  // ── Expense Categories ──────────────────────────────────────────────
  EXPENSE_CATEGORIES: {
    FOOD: 'Food',
    TRAVEL: 'Travel',
    ACCOMMODATION: 'Accommodation',
    TRANSPORT: 'Transport',
    OFFICE_SUPPLIES: 'Office Supplies',
    SOFTWARE: 'Software & Subscriptions',
    COMMUNICATION: 'Communication',
    MEDICAL: 'Medical',
    ENTERTAINMENT: 'Entertainment',
    SHOPPING: 'Shopping',
    FUEL: 'Fuel',
    MAINTENANCE: 'Maintenance',
    OTHER: 'Other'
  },

  // ── AI Category Detection — Weighted Keyword Dictionary ─────────────

  CATEGORY_KEYWORDS: {
    Food: [
      // Known food delivery / restaurant brands
      { keyword: 'zomato', weight: 10 },
      { keyword: 'swiggy', weight: 10 },
      { keyword: 'uber eats', weight: 10 },
      { keyword: 'ubereats', weight: 10 },
      { keyword: 'doordash', weight: 10 },
      { keyword: 'grubhub', weight: 10 },
      { keyword: 'dominos', weight: 10 },
      { keyword: 'domino', weight: 10 },
      { keyword: 'pizza hut', weight: 10 },
      { keyword: 'mcdonald', weight: 10 },
      { keyword: 'mcdonalds', weight: 10 },
      { keyword: 'burger king', weight: 10 },
      { keyword: 'kfc', weight: 10 },
      { keyword: 'subway', weight: 10 },
      { keyword: 'starbucks', weight: 10 },
      { keyword: 'cafe coffee day', weight: 10 },
      { keyword: 'ccd', weight: 8 },
      { keyword: 'dunkin', weight: 10 },
      { keyword: 'haldiram', weight: 10 },
      { keyword: 'barbeque nation', weight: 10 },

      // Generic food terms
      { keyword: 'restaurant', weight: 7 },
      { keyword: 'cafe', weight: 6 },
      { keyword: 'bistro', weight: 6 },
      { keyword: 'diner', weight: 6 },
      { keyword: 'food', weight: 5 },
      { keyword: 'meal', weight: 5 },
      { keyword: 'lunch', weight: 5 },
      { keyword: 'dinner', weight: 5 },
      { keyword: 'breakfast', weight: 5 },
      { keyword: 'snack', weight: 4 },
      { keyword: 'beverage', weight: 4 },
      { keyword: 'coffee', weight: 4 },
      { keyword: 'tea', weight: 3 },
      { keyword: 'biryani', weight: 5 },
      { keyword: 'pizza', weight: 5 },
      { keyword: 'burger', weight: 5 },
      { keyword: 'chicken', weight: 3 },
      { keyword: 'noodle', weight: 4 },
      { keyword: 'bakery', weight: 6 },
      { keyword: 'catering', weight: 5 },
      { keyword: 'kitchen', weight: 4 },
      { keyword: 'grill', weight: 5 },
      { keyword: 'dhaba', weight: 6 },
      { keyword: 'dine in', weight: 7 },
      { keyword: 'dine-in', weight: 7 },
      { keyword: 'take away', weight: 6 },
      { keyword: 'takeaway', weight: 6 },
      { keyword: 'veg', weight: 4 },
      { keyword: 'non veg', weight: 5 },
      { keyword: 'non-veg', weight: 5 },
      { keyword: 'paneer', weight: 5 },
      { keyword: 'naan', weight: 5 },
      { keyword: 'roti', weight: 5 },
      { keyword: 'dal', weight: 4 },
      { keyword: 'curry', weight: 5 },
      { keyword: 'rice', weight: 3 },
      { keyword: 'taco', weight: 5 },
      { keyword: 'burrito', weight: 5 },
      { keyword: 'mexicana', weight: 5 },
      { keyword: 'garlic', weight: 4 },
      { keyword: 'masala', weight: 5 },
      { keyword: 'tandoori', weight: 5 },
      { keyword: 'kebab', weight: 5 },
      { keyword: 'wrap', weight: 3 },
      { keyword: 'salad', weight: 4 },
      { keyword: 'soup', weight: 4 },
      { keyword: 'dessert', weight: 4 },
      { keyword: 'ice cream', weight: 4 },
      { keyword: 'waiter', weight: 5 },
      { keyword: 'server', weight: 3 },
      { keyword: 'table', weight: 3 },
      { keyword: 'bill', weight: 3 },
    ],

    Travel: [
      // Known travel platforms / airlines
      { keyword: 'makemytrip', weight: 10 },
      { keyword: 'make my trip', weight: 10 },
      { keyword: 'goibibo', weight: 10 },
      { keyword: 'cleartrip', weight: 10 },
      { keyword: 'yatra', weight: 10 },
      { keyword: 'booking.com', weight: 10 },
      { keyword: 'expedia', weight: 10 },
      { keyword: 'kayak', weight: 10 },
      { keyword: 'skyscanner', weight: 10 },
      { keyword: 'indigo', weight: 8 },
      { keyword: 'air india', weight: 10 },
      { keyword: 'spicejet', weight: 10 },
      { keyword: 'vistara', weight: 10 },
      { keyword: 'emirates', weight: 10 },
      { keyword: 'lufthansa', weight: 10 },
      { keyword: 'british airways', weight: 10 },
      { keyword: 'irctc', weight: 10 },
      { keyword: 'redbus', weight: 10 },
      // Generic travel terms
      { keyword: 'flight', weight: 7 },
      { keyword: 'airline', weight: 7 },
      { keyword: 'boarding pass', weight: 8 },
      { keyword: 'boarding', weight: 5 },
      { keyword: 'itinerary', weight: 6 },
      { keyword: 'ticket', weight: 4 },
      { keyword: 'travel', weight: 5 },
      { keyword: 'trip', weight: 4 },
      { keyword: 'journey', weight: 4 },
      { keyword: 'airport', weight: 6 },
      { keyword: 'terminal', weight: 4 },
      { keyword: 'departure', weight: 5 },
      { keyword: 'arrival', weight: 5 },
      { keyword: 'passport', weight: 5 },
      { keyword: 'visa', weight: 4 },
      { keyword: 'railway', weight: 6 },
      { keyword: 'train', weight: 5 },
      { keyword: 'pnr', weight: 6 },
      { keyword: 'bus ticket', weight: 6 },
    ],

    Accommodation: [
      // Known hotel / stay brands
      { keyword: 'oyo', weight: 10 },
      { keyword: 'airbnb', weight: 10 },
      { keyword: 'marriott', weight: 10 },
      { keyword: 'hilton', weight: 10 },
      { keyword: 'hyatt', weight: 10 },
      { keyword: 'taj hotel', weight: 10 },
      { keyword: 'oberoi', weight: 10 },
      { keyword: 'lemon tree', weight: 10 },
      { keyword: 'treebo', weight: 10 },
      { keyword: 'fabhotel', weight: 10 },
      { keyword: 'trivago', weight: 10 },

      // Generic accommodation terms
      { keyword: 'hotel', weight: 7 },
      { keyword: 'motel', weight: 7 },
      { keyword: 'resort', weight: 7 },
      { keyword: 'lodge', weight: 6 },
      { keyword: 'inn', weight: 5 },
      { keyword: 'guest house', weight: 6 },
      { keyword: 'hostel', weight: 6 },
      { keyword: 'check-in', weight: 5 },
      { keyword: 'check-out', weight: 5 },
      { keyword: 'room charge', weight: 7 },
      { keyword: 'room', weight: 3 },
      { keyword: 'stay', weight: 3 },
      { keyword: 'accommodation', weight: 7 },
      { keyword: 'night', weight: 3 },
    ],

    Transport: [
      // Known ride-share / cab brands
      { keyword: 'uber', weight: 10 },
      { keyword: 'ola', weight: 10 },
      { keyword: 'lyft', weight: 10 },
      { keyword: 'rapido', weight: 10 },
      { keyword: 'meru', weight: 10 },
      { keyword: 'blablacar', weight: 10 },


      // Generic transport terms
      { keyword: 'cab', weight: 7 },
      { keyword: 'taxi', weight: 7 },
      { keyword: 'ride', weight: 5 },
      { keyword: 'auto', weight: 4 },
      { keyword: 'rickshaw', weight: 6 },
      { keyword: 'metro', weight: 6 },
      { keyword: 'bus', weight: 4 },
      { keyword: 'parking', weight: 6 },
      { keyword: 'toll', weight: 6 },
      { keyword: 'fare', weight: 5 },
      { keyword: 'driver', weight: 4 },
      { keyword: 'pickup', weight: 4 },
      { keyword: 'dropoff', weight: 4 },
      { keyword: 'drop off', weight: 4 },
      { keyword: 'distance', weight: 3 },
      { keyword: 'km', weight: 3 },
    ],

    Fuel: [
      // Known fuel brands
      { keyword: 'indian oil', weight: 10 },
      { keyword: 'iocl', weight: 10 },
      { keyword: 'bharat petroleum', weight: 10 },
      { keyword: 'bpcl', weight: 10 },
      { keyword: 'hp petrol', weight: 10 },
      { keyword: 'hindustan petroleum', weight: 10 },
      { keyword: 'hpcl', weight: 10 },
      { keyword: 'shell', weight: 7 },
      { keyword: 'reliance petrol', weight: 10 },
      // Generic fuel terms
      { keyword: 'petrol', weight: 8 },
      { keyword: 'diesel', weight: 8 },
      { keyword: 'gasoline', weight: 8 },
      { keyword: 'fuel', weight: 7 },
      { keyword: 'gas station', weight: 8 },
      { keyword: 'pump', weight: 4 },
      { keyword: 'litre', weight: 4 },
      { keyword: 'liter', weight: 4 },
      { keyword: 'gallon', weight: 4 },
    ],

    'Office Supplies': [
      { keyword: 'staples', weight: 10 },
      { keyword: 'office depot', weight: 10 },
      { keyword: 'stationery', weight: 7 },
      { keyword: 'pen', weight: 3 },
      { keyword: 'paper', weight: 3 },
      { keyword: 'printer', weight: 5 },
      { keyword: 'cartridge', weight: 5 },
      { keyword: 'toner', weight: 5 },
      { keyword: 'notebook', weight: 4 },
      { keyword: 'office supply', weight: 7 },
      { keyword: 'whiteboard', weight: 5 },
      { keyword: 'marker', weight: 3 },
      { keyword: 'folder', weight: 3 },
      { keyword: 'desk', weight: 3 },
      { keyword: 'chair', weight: 3 },
      { keyword: 'furniture', weight: 4 },
    ],

    'Software & Subscriptions': [
      { keyword: 'github', weight: 10 },
      { keyword: 'aws', weight: 10 },
      { keyword: 'google cloud', weight: 10 },
      { keyword: 'azure', weight: 10 },
      { keyword: 'jira', weight: 10 },
      { keyword: 'atlassian', weight: 10 },
      { keyword: 'slack', weight: 10 },
      { keyword: 'zoom', weight: 10 },
      { keyword: 'notion', weight: 10 },
      { keyword: 'figma', weight: 10 },
      { keyword: 'adobe', weight: 10 },
      { keyword: 'microsoft', weight: 7 },
      { keyword: 'office 365', weight: 10 },
      { keyword: 'netflix', weight: 8 },
      { keyword: 'spotify', weight: 8 },
      { keyword: 'subscription', weight: 6 },
      { keyword: 'license', weight: 5 },
      { keyword: 'saas', weight: 6 },
      { keyword: 'software', weight: 5 },
      { keyword: 'renewal', weight: 4 },
      { keyword: 'plan', weight: 3 },
      { keyword: 'annual', weight: 3 },
      { keyword: 'monthly', weight: 3 },
    ],

    Communication: [
      { keyword: 'airtel', weight: 10 },
      { keyword: 'jio', weight: 10 },
      { keyword: 'vodafone', weight: 10 },
      { keyword: 'bsnl', weight: 10 },
      { keyword: 'vi ', weight: 8 },
      { keyword: 't-mobile', weight: 10 },
      { keyword: 'verizon', weight: 10 },
      { keyword: 'at&t', weight: 10 },
      { keyword: 'telecom', weight: 6 },
      { keyword: 'mobile', weight: 4 },
      { keyword: 'recharge', weight: 6 },
      { keyword: 'phone bill', weight: 7 },
      { keyword: 'internet', weight: 5 },
      { keyword: 'broadband', weight: 6 },
      { keyword: 'wifi', weight: 5 },
      { keyword: 'data pack', weight: 6 },
      { keyword: 'postpaid', weight: 6 },
      { keyword: 'prepaid', weight: 6 },
      { keyword: 'sim', weight: 4 },
    ],

    Medical: [
      { keyword: 'apollo', weight: 10 },
      { keyword: 'medplus', weight: 10 },
      { keyword: 'practo', weight: 10 },
      { keyword: 'pharmeasy', weight: 10 },
      { keyword: 'netmeds', weight: 10 },
      { keyword: 'hospital', weight: 8 },
      { keyword: 'clinic', weight: 7 },
      { keyword: 'pharmacy', weight: 7 },
      { keyword: 'medical', weight: 6 },
      { keyword: 'doctor', weight: 6 },
      { keyword: 'prescription', weight: 7 },
      { keyword: 'medicine', weight: 6 },
      { keyword: 'tablet', weight: 4 },
      { keyword: 'health', weight: 4 },
      { keyword: 'diagnostic', weight: 6 },
      { keyword: 'lab test', weight: 7 },
      { keyword: 'pathology', weight: 6 },
      { keyword: 'consultation', weight: 5 },
      { keyword: 'therapy', weight: 5 },
    ],

    Entertainment: [
      { keyword: 'bookmyshow', weight: 10 },
      { keyword: 'book my show', weight: 10 },
      { keyword: 'pvr', weight: 10 },
      { keyword: 'inox', weight: 10 },
      { keyword: 'multiplex', weight: 8 },
      { keyword: 'cinema', weight: 7 },
      { keyword: 'movie', weight: 6 },
      { keyword: 'theatre', weight: 6 },
      { keyword: 'theater', weight: 6 },
      { keyword: 'concert', weight: 7 },
      { keyword: 'event', weight: 4 },
      { keyword: 'amusement', weight: 6 },
      { keyword: 'theme park', weight: 6 },
      { keyword: 'game', weight: 3 },
      { keyword: 'bowling', weight: 5 },
      { keyword: 'sport', weight: 3 },
    ],

    Shopping: [
      { keyword: 'amazon', weight: 10 },
      { keyword: 'flipkart', weight: 10 },
      { keyword: 'myntra', weight: 10 },
      { keyword: 'ajio', weight: 10 },
      { keyword: 'reliance digital', weight: 10 },
      { keyword: 'croma', weight: 10 },
      { keyword: 'dmart', weight: 10 },
      { keyword: 'big bazaar', weight: 10 },
      { keyword: 'walmart', weight: 10 },
      { keyword: 'target', weight: 7 },
      { keyword: 'shopping', weight: 6 },
      { keyword: 'mall', weight: 5 },
      { keyword: 'retail', weight: 5 },
      { keyword: 'store', weight: 3 },
      { keyword: 'purchase', weight: 3 },
      { keyword: 'order', weight: 3 },
      { keyword: 'delivery', weight: 3 },
    ],

    Maintenance: [
      { keyword: 'repair', weight: 7 },
      { keyword: 'maintenance', weight: 7 },
      { keyword: 'plumber', weight: 7 },
      { keyword: 'electrician', weight: 7 },
      { keyword: 'service', weight: 3 },
      { keyword: 'amc', weight: 6 },
      { keyword: 'cleaning', weight: 5 },
      { keyword: 'pest control', weight: 7 },
      { keyword: 'hvac', weight: 6 },
      { keyword: 'technician', weight: 5 },
      { keyword: 'fix', weight: 3 },
    ],
  },

  // ── Currency symbol to code mapping ─────────────────────────────────
  CURRENCY_SYMBOLS: {
    '₹': 'INR',
    '$': 'USD',
    '€': 'EUR',
    '£': 'GBP',
    '¥': 'JPY',
    '₩': 'KRW',
    '฿': 'THB',
    '₫': 'VND',
    '₱': 'PHP',
    'AED': 'AED',
    'SAR': 'SAR',
    'Rs': 'INR',
    'Rs.': 'INR',
    'INR': 'INR',
    'USD': 'USD',
    'EUR': 'EUR',
    'GBP': 'GBP',
  }
};
